### ISSUE TITLE
A little change needed

### ISSUE THREAD

**Issue by limelect** [corneliusdavid/AutoGetIt#6]
Now it works for 10.2.3
However, how do you filter for free paid and more?
Trying once more DOS COMMAND still running !!!
Compiling with D10.2.3

OK on the run button I added
if DosCommand.IsRunning then DosCommand.Stop;

And one more running under IDE can only see the installed 
otherwise running a program without ide is OK.

Another one if the line is long of the component it goes to next line then you have a check box
which is not supposed to see
See Ribbon
Add print feature

**Comment by corneliusdavid** [comment]
I don't filter for free or paid with the command-line version because GetItCmd doesn't support that.

I didn't bother disabling the "Install Checked" button (I assume that's what you mean by "run button") because it's on the background form during installation--why would someone click that? I suppose that could be done to make it a little more robust.

I don't know what you mean about running under IDE can see only the installed.

Long-line wrap-around: yes, that's the limitation of doing this with just the GetItCmd interface and using DosCommand to capture the output. I'm working on the API version which will have a lot more control of the display--and a lot more information available.

I'll think about adding a print feature but not sure how valuable that would be.  Feel free to submit a pull request with it implemented.

**Comment by limelect** [comment]
"I don't know what you mean about running under IDE can see only the installed."

I do not think it is your problem.
but when running in IDE I see only the installed and
for ALL I see an EMPTY screen.
Running the program outside the IDE is OK.

The most important
"I don't filter for free or paid with the command-line version because GetItCmd doesn't support that."
I know you cannot help.

I meant "&Refresh Package List" button.
Very important  I added the line (otherwise  DosCommand is stuck on second time)

if DosCommand.IsRunning then DosCommand.Stop;<<<<<<<<<<<<< add this

**Comment by corneliusdavid** [comment]
When the install starts, a separate window pops up over the main window. The new window is a log of the GetItCmd output and contains a Cancel button that calls DosCommand.Stop. In order to get to the Refresh button that you're referring to, you have to move that new window out of the way. Adding DosCommand.Stop to the Refresh button does not make sense; instead, I have disabled it during install/uninstall, just like the I did with the Install/Uninstall actions (even though it's hard to get to and I don't understand why it's a problem).
